name: Deploy to WP Engine

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Get full history, not shallow clone
      
    - name: Setup SSH
      run: |
        # Create SSH directory
        mkdir -p $HOME/.ssh
        
        # Add WP Engine SSH key (ED25519 format)
        # yamllint disable-line
        echo "${{ secrets.WPE_SSHG_KEY_PRIVATE }}" > $HOME/.ssh/wpengine_ed25519
        chmod 600 $HOME/.ssh/wpengine_ed25519
        
        # Generate public key from private key
        ssh-keygen -y -f $HOME/.ssh/wpengine_ed25519 > $HOME/.ssh/wpengine_ed25519.pub
        
        # Debug: Show key fingerprints
        echo "=== SSH Key Fingerprints ==="
        echo "MD5 fingerprint:"
        ssh-keygen -l -E md5 -f $HOME/.ssh/wpengine_ed25519.pub
        echo "SHA256 fingerprint:"
        ssh-keygen -l -E sha256 -f $HOME/.ssh/wpengine_ed25519.pub
        
        # Debug: Check key format (first and last lines only for security)
        echo -e "\n=== Key format check ==="
        head -n 1 $HOME/.ssh/wpengine_ed25519
        tail -n 1 $HOME/.ssh/wpengine_ed25519
        
        # Configure SSH to use the key
        cat >> $HOME/.ssh/config <<END
        Host git.wpengine.com
          HostName git.wpengine.com
          User git
          IdentityFile $HOME/.ssh/wpengine_ed25519
          IdentitiesOnly yes
          StrictHostKeyChecking no
          PreferredAuthentications publickey
          LogLevel DEBUG
        END
        
        # Test SSH connection
        ssh-keyscan -H git.wpengine.com >> $HOME/.ssh/known_hosts
        
    - name: Test SSH Connection
      run: |
        # Show the public key for debugging
        echo "=== Public key content ==="
        cat $HOME/.ssh/wpengine_ed25519.pub
        
        # Test the SSH connection to WP Engine
        echo -e "\n=== Testing SSH connection to WP Engine ==="
        ssh -vT git@git.wpengine.com 2>&1 | grep -E "(debug1:|Hi|hello|Permission|publickey)" || true
        echo "SSH test completed."
        
    - name: Add WP Engine remote
      run: |
        # Add WP Engine as a remote if it doesn't exist
        git remote | grep -q wpengine || git remote add wpengine git@git.wpengine.com:alepodev.git
        
    - name: Deploy to WP Engine
      env:
        WPE_ENV: alepodev
        SRC_PATH: '.'
        REMOTE_PATH: '.'
        FLAGS: '--delete'
      run: |
        # Create deployment branch
        git checkout -b deploy-${{ github.sha }}
        
        # Configure git
        git config user.email "github-actions@github.com"
        git config user.name "GitHub Actions"
        
        # Create .gitignore for WP Engine deployment
        cat > .gitignore <<EOF
        # Exclude documentation and development files from deployment
        alepo-docs/
        .github/
        tools/deprecated/
        tools/theme-utilities/debug-*.html
        *.md
        .git*
        node_modules/
        .env
        .DS_Store
        *.log
        EOF
        
        # Add and commit deployment-ready files
        git add -A
        git commit -m "Deploy to WP Engine: ${{ github.sha }}" || echo "No changes to commit"
        
        # Force push to WP Engine
        echo "Pushing to WP Engine..."
        git push -v wpengine deploy-${{ github.sha }}:master --force 2>&1 || {
          echo "Push failed. Trying alternative branch name..."
          git push -v wpengine deploy-${{ github.sha }}:main --force 2>&1
        }
        
    - name: Cleanup
      if: always()
      run: |
        # Return to main branch
        git checkout main || true
        # Delete deployment branch
        git branch -D deploy-${{ github.sha }} || true