name: Simple WP Engine Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'WP Engine Environment'
        required: true
        default: 'alepodev'
        type: choice
        options:
          - alepodev

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Get full history
      
    - name: Setup Git and SSH
      run: |
        # Configure Git
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        
        # Setup SSH
        mkdir -p ~/.ssh
        echo "${{ secrets.WPE_SSHG_KEY_PRIVATE }}" > ~/.ssh/wpengine_key
        chmod 600 ~/.ssh/wpengine_key
        
        # Generate public key and show fingerprints
        ssh-keygen -y -f ~/.ssh/wpengine_key > ~/.ssh/wpengine_key.pub
        echo "=== SSH Key Fingerprints ==="
        echo "MD5 fingerprint:"
        ssh-keygen -l -E md5 -f ~/.ssh/wpengine_key.pub
        echo "SHA256 fingerprint:"
        ssh-keygen -l -E sha256 -f ~/.ssh/wpengine_key.pub
        
        # Add SSH config
        cat >> ~/.ssh/config <<EOF
        Host *.wpengine.com
          User git
          IdentityFile ~/.ssh/wpengine_key
          StrictHostKeyChecking no
          IdentitiesOnly yes
        EOF
        
        # Test connection
        ssh-keyscan -t ed25519,rsa git.wpengine.com >> ~/.ssh/known_hosts
        
    - name: Test WP Engine Connection
      run: |
        echo "Testing connection..."
        ssh -T git@git.wpengine.com || echo "Connection test completed"
        
    - name: Add WP Engine Remote
      run: |
        # Remove existing remote if present
        git remote remove wpengine || true
        
        # Add WP Engine remote
        git remote add wpengine git@git.wpengine.com:${{ inputs.environment }}.git
        
        # Show remotes
        git remote -v
        
    - name: Deploy to WP Engine
      run: |
        echo "Deploying to ${{ inputs.environment }}..."
        
        # Push current branch to WP Engine master
        git push wpengine HEAD:master --force